 channels:
     - conda-forge
 dependencies:
     - python 3.9
     - pip==22.1.2
     - numpy==1.23.0
     - face_recognition==1.3.0
     - streamlit_webrtc==0.42.0
     - pip:
          - opencv_python==4.6.0.66
