 channels:
     - conda-forge
 dependencies:
     - face_recognition==1.3.0
     - numpy==1.23.0
     - Pillow==9.2.0
     - pip==22.1.2
     - pip:
         - opencv_python==4.6.0.66
         - mediapipe==0.8.10